
---
PCA
---

```{r}
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library("ggplot2") 
install.packages("adegenet", repos = "http://cran.us.r-project.org") 
library("adegenet") 
install.packages("dplyr", repos = "http://cran.us.r-project.org") 
library("dplyr") 
install.packages("poppr", repos = "http://cran.us.r-project.org") 
library("poppr") 
install.packages("hierfstat", repos = "http://cran.us.r-project.org") 
library("hierfstat") 
install.packages("reshape2", repos = "http://cran.us.r-project.org") 
library("reshape2") 
install.packages("scales", repos = "http://cran.us.r-project.org") 
library("scales") 
install.packages("RColorBrewer", repos = "http://cran.us.r-project.org") 
library("RColorBrewer") 
install.packages("diveRsity", repos = "http://cran.us.r-project.org") 
library("RColorBrewer") 
```



```{r}
Brown.Trout = read.genepop('/Users/nooralwash/Downloads/DataR_2.gen', ncode = 3L)

```


#2 print
```{r}
Brown.Trout
```

```{r}
popNames(Brown.Trout) = c("CHB","RHB","CHR","RHR","CHC","RHC","CKB","RKB","CKR","RKR","CKC","RKC","CVB","RVB","CVR","RVR","CVC","RVC", "CSB","RSB","CSR","RSR","CSC","RSC")
```


```{r}
Brown.Trout_sub = popsub (Brown.Trout, sublist = c("CHB","RHB","CHR","RHR","CHC","RHC","CKB","RKB","CKR","RKR","CKC","RKC","CVB","RVB","CVR","RVR","CVC","RVC", "CSB","RSB","CSR","RSR","CSC","RSC"))

Brown.Trout_sub
```


```{r}
# Perform cross validation to find the optimal number of PCs to retain in DAPC (Discriminant Analysis Machine Learning model cross validation: Building and cross validating a model that can predict future samples belonging to which population)
set.seed(123)
x = tab(Brown.Trout_sub, NA.method = "mean")
crossval = xvalDapc(x, Brown.Trout_sub$pop, result = "groupMean", xval.plot = TRUE)

```

```{r}
# Number of PCs with best stats (lower score = better)
crossval$`Root Mean Squared Error by Number of PCs of PCA`
##        20        40        60        80       100       120       140 
## 0.7072406 0.6354916 0.6501085 0.6206800 0.6247699 0.6145408 0.6140150
crossval$`Number of PCs Achieving Highest Mean Success`
## [1] "120"
crossval$`Number of PCs Achieving Lowest MSE`
## [1] "140"
numPCs = as.numeric(crossval$`Number of PCs Achieving Lowest MSE`)
```



```{r}
# Run a DAPC using site IDs as priors
dapc1 = dapc(Brown.Trout_sub, Brown.Trout_sub$pop, n.pca = numPCs, n.da = 3)

# Analyse how much percent of genetic variance is explained by each axis
percent = dapc1$eig/sum(dapc1$eig)*100
barplot(percent, ylab = "Genetic variance explained by eigenvectors (%)", ylim = c(0,60),
        names.arg = round(percent, 1))
```

```{r}
# Replace missing data with the mean allele frequencies
x = tab(Brown.Trout_sub, NA.method = "mean")

# Perform PCA
pca1 = dudi.pca(x, scannf = FALSE, scale = FALSE, nf = 3)

# Analyse how much percent of genetic variance is explained by each axis
percent = pca1$eig/sum(pca1$eig)*100
barplot(percent, ylab = "Genetic variance explained by eigenvectors (%)", ylim = c(0,12),
        names.arg = round(percent, 1))
```



```{r}

x = tab(Brown.Trout_sub, NA.method = "mean")
pca1 = dudi.pca(x, scannf = FALSE, scale = TRUE, nf = 3)
percent = pca1$eig/sum(pca1$eig)*100
ind_coords = as.data.frame(pca1$li)
colnames(ind_coords) = c("Axis1","Axis2","Axis3")
ind_coords$Ind = indNames(Brown.Trout_sub)
ind_coords$Site = Brown.Trout_sub$pop
centroid = aggregate(cbind(Axis1, Axis2, Axis3) ~ Site, data = ind_coords, FUN = mean)
ind_coords = left_join(ind_coords, centroid, by = "Site", suffix = c("",".cen"))
cols = c("#ADD8E6", "#7400DF", "#9C00C0", "#B700A1" , "#CC0083", "#DC0066" ,"#EB0048", "#F70026", "#FD2B10", "#F85C34", "#EF7C53", "#E39871", "red", "#BBC9B1", "#97E0D2", "yellow", "#28FEED", "#3BFED4", "#7FFF00", "#45FEA0", "#42FE84" ,"#3AFE67", "#2BFE45" ,"#00FF00")

xlab = paste("Axis 1 (", format(round(percent[1], 1), nsmall=1)," %)", sep="")
ylab = paste("Axis 2 (", format(round(percent[2], 1), nsmall=1)," %)", sep="")
ggplot(data = ind_coords, aes(x = Axis1, y = Axis2))+
  
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_segment(aes(xend = Axis1.cen, yend = Axis2.cen, colour = Site), show.legend = FALSE, alpha = 0.5)+
  geom_point(aes(fill = Site), shape = 21, size = 2, show.legend = FALSE, alpha = 0.5)+
  geom_label(data = centroid, aes(label = Site, fill = Site), size = 1.8, show.legend = FALSE)+
  scale_fill_manual(values = cols)+
  scale_colour_manual(values = cols)+
  labs(x = xlab, y = ylab)+
  ggtitle(" ")+
theme(panel.background = element_rect(fill = "white")) # Add this line


#  +geom_label_repel(data = centroid, aes(label = Site, fill = Site), size = 4, show.legend = FALSE,
 #                  min.segment.length = 0.5, segment.linetype = 3)



```

